// #Misfits Add - Door Logs tab for admin menu
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Administration.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class DoorLogsTab : Control
{
    public DoorLogsTab()
    {
        RobustXamlLoader.Load(this);

        OpenLogsButton.Text = GetLocalizedOrFallback(
            "misfits-logs-tab-open-logs-btn",
            "Logs");
        OpenLogsDescription.Text = GetLocalizedOrFallback(
            "misfits-logs-tab-open-logs-desc",
            "Open the regular admin logs viewer.");

        OpenDoorLogsButton.Text = GetLocalizedOrFallback(
            "misfits-logs-tab-open-door-logs-btn",
            "Door Logs");
        OpenDoorLogsDescription.Text = GetLocalizedOrFallback(
            "misfits-logs-tab-open-door-logs-desc",
            "View the door destruction log - which doors were destroyed and by whom.");

        OpenWhitelistLogsButton.Text = GetLocalizedOrFallback(
            "misfits-logs-tab-open-whitelist-logs-btn",
            "Whitelist Logs");
        OpenWhitelistLogsDescription.Text = GetLocalizedOrFallback(
            "misfits-logs-tab-open-whitelist-logs-desc",
            "View whitelist grants and removals in a dedicated log.");
    }

    /// <summary>
    /// Returns a localized string or a fallback if the locale key is missing.
    /// </summary>
    private static string GetLocalizedOrFallback(string key, string fallback)
    {
        var loc = IoCManager.Resolve<ILocalizationManager>();
        if (loc.TryGetString(key, out var localized))
            return localized;
        return fallback;
    }
}
