# #Misfits Change /Add/: Legion Auxilia job.
- type: job
  id: CaesarLegionAuxilia
  setPreference: true
  hideIfPlaytimeRequirementsNotMet: false # #Misfits Tweak - all jobs visible in selection
  jobWhitelistBypassesRoleTimers: true # #Misfits Change
  weight: 30
  name: job-name-caesar-legion-auxilia
  description: job-description-caesar-legion-auxilia
  playTimeTracker: CaesarLegionAuxilia
  requirements:
  #  - !type:CharacterDepartmentTimeRequirement # #Misfits Tweak - T2 faction timelock (4h Legion)
  #   department: CaesarLegion
  #    min: 14400 # 4 hours
    #- !type:CharacterPlaytimeRequirement # TEMP REMOVED
    #  tracker: CaesarLegionRecruit
    #  min: 10800 # 3 hours
    - !type:CharacterSpeciesRequirement
      species:
      - Human
  startingGear: CaesarLegionAuxiliaGear
  alwaysUseSpawner: true
  icon: "JobIconlegionerRecruit"
  supervisors: job-name-caesar-legion-other
  canBeAntag: false
  accessGroups:
  - CaesarLegionRecruit
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - CaesarLegion
      - type: ReplacementAccent
        accent: latin
      - type: CPRTraining
  - !type:AddTraitSpecial
    traits: [ LanguageLatin ]

- type: startingGear
  id: CaesarLegionAuxiliaGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitLegionnaire
    ears: N14ClothingHeadsetLegion
    mask: N14ClothingMaskBrownMask
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsLeather
    head: N14ClothingHeadHatTribalOutcastHood
    gloves: N14ClothingHandsGlovesTribal
    pocket1: LegionAuxilialoadoutkits
    id: N14IDLegionaryBadge
  innerClothingSkirt: N14ClothingUniformJumpsuitLegionnaireOther
  storage:
    back:
    - N14BoxPlasticFilledMilitaryLegion #Misfits Change /Tweak/: Legion uses tribal medicine, not stimpaks
    - N14HealingPowder
    - N14HealingPowder
    - N14HealingPoultice
    - N14HealingPoultice
    - N14Hydra

- type: playTimeTracker
  id: CaesarLegionAuxilia
