- type: loadout
  id: LoadoutLegionPrinceps
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - CaesarLegionVeteranDecanus
    - !type:CharacterPlaytimeRequirement
      tracker: CaesarLegionVeteranDecanus
      min: 90000 # 25 hours
  items:
    - MisfitsLegionPrincepsArmor
    - MisfitsLegionPrincepsHelmet
    - MisfitsLegionPrincepsGloves
    - MisfitsLegionPrincepsBoots
